### ISSUE TITLE
JOIN returns incorrect result when used with nested SELECT

### ISSUE THREAD

**Issue by akhaneev** [AlaSQL/alasql#1263] opened 2020-12-03 15:35 UTC
Here is a test:

```
if (typeof exports === 'object') {
    var assert = require('assert');
    var alasql = require('..');
} else {
    __dirname = '.';
}

describe('Test 813 - Nested SELECT', function () {
    var t1 = [
        {id: '1', a: 'one'},
        {id: '2', a: 'two'},
        {id: '3', a: 'three'},
        {id: '4', a: 'four'},
    ];
    var t2 = [
        {id: '1', b: 'A'},
        {id: '2', b: 'B'},
        {id: '5', b: 'E'},
        {id: '6', b: 'F'},
    ];

    it('1. JOIN', function (done) {
        var expected = [
            {id: '1', a: 'one', b: 'A'},
            {id: '2', a: 'two', b: 'B'},
            {id: '3', a: 'three'},
            {id: '4', a: 'four'},
            {id: '5', b: 'E'},
            {id: '6', b: 'F'},
        ];

        var res = alasql(
            'SELECT * FROM ? T1 OUTER JOIN ? T2 ON T1.id = T2.id',
            [t1, t2]
        );
        assert.deepEqual(res, expected);

        var res = alasql(
            'SELECT * FROM ? T1 OUTER JOIN (SELECT * FROM ?) T2 ON T1.id = T2.id',
            [t1, t2]
        );
        assert.deepEqual(res, expected);
        done();
    });

});

```

**Comment by mathiasrw** [comment] 2020-12-05 02:25
Thank you so much for identifying this bug so precise.

**Comment by journeytoday** [comment] 2023-09-24 05:45
Hi @akhaneev  @mathiasrw this is closed but shows open in good first issue, is this by design or a bug?

**Comment by mathiasrw** [comment] 2023-09-25 00:53
@journeytoday Great work picking this up. I added the test from this PR and I can see that its working as expected. Will close this one. Thank you for pinging me on this.

**Closed by mathiasrw** 2023-09-25 00:53 UTC
Labels: ! Bug, Help wanted, Related to: SQL compliance, Bug: Code provided to reproduced, Good first issue
