### ISSUE TITLE
alasql is not defined

### ISSUE THREAD

**Issue by jethroguce** [AlaSQL/alasql#388] opened 2015-08-11 01:37 UTC
I have an AngularJS application using requireJS, I have imported the alasql.min.js but I am having an issue with `alasql is not defined'

**Comment by jethroguce** [comment] 2015-08-11 02:44
i just called the file normally, without using requirejs

**Comment by mathiasrw** [comment] 2015-08-11 06:08
Good to hear you found a solution. 

I have updated https://github.com/agershun/alasql/wiki/Angular.js to make sure others can learn from this issue

**Comment by jethroguce** [comment] 2015-08-12 04:03
it's not actually a solution, more of a work around, I still haven't found a solution with require.

**Comment by hsHemant** [comment] 2015-09-15 16:18
Hi jethroguce, please tell me how you used.

**Comment by ThinklabsGbR** [comment] 2015-09-15 16:35
maybe fixed with #410 solution by @pboos

**Comment by mathiasrw** [comment] 2015-09-16 09:31
For others seeking to use normally: check out: https://github.com/agershun/alasql/issues/417#issuecomment-140683103

@jethroguce super true - its not a solution. If you have time to dig into where the problem lays that would be awesome.

**Comment by keeganmccallum** [comment] 2016-04-19 18:33
I found the issue is isolated to line 17258 of the unminified dist file. i.e.:
        
    if(typeof exports !== 'object') {
        alasql.worker = function(path, paths, cb) {
        .......

with requireJS alasql is not available globally, so this throws a reference error. I am not familiar enough with the codebase to offer a fix/pull request, but just commenting short-circuiting that if statement solves the problem(although I would assume worker support is not available).

**Comment by mathiasrw** [comment] 2016-04-21 04:57
Nice - thank you so much for getting back with the information. 

I have changed the code locally, but I am having some issues with compiling. Ill get back to you as soon as I have the new code up.

**Comment by mathiasrw** [comment] 2016-04-21 05:30
@keeganmccallum 

Can I ask you to try https://github.com/agershun/alasql/blob/develop/dist/alasql.js and see if this solves the problem for now?

**Comment by keeganmccallum** [comment] 2016-04-27 16:43
exact same issue occurs for me with that file, code in question starts at line 17280 now though

**Comment by sorb999** [comment] 2016-12-22 05:53
I am getting same error, When I am trying to use it with requireJS or Even if I am trying to reference it directly to html, 
Is there any solution to use it with angularJS and requireJS?

**Comment by jethroguce** [comment] 2016-12-22 10:54
@sorb999 you would need to import the source files before requireJS

**Closed** 2023-07-30 15:10 UTC
Labels: ! Bug, Help wanted
