### ISSUE TITLE
ORDER BY and dates issue

### ISSUE THREAD

**Issue by fabads** [AlaSQL/alasql#1513] opened 2022-10-05 16:29 UTC
Hello, 
I encounter an issue trying to ordering my data containing date columns.

Here an example of code (Apps script):

```
function myTest() {
  var data =[{id: 200, fromDate: new Date("2022-11-29"), toDate: new Date("2022-11-29")}, 
    {id:  100, fromDate: new Date("2022-11-30"), toDate: new Date("2022-11-30")},
    {id:  101, fromDate: new Date("2022-11-30"), toDate: new Date("2022-11-30")}, 
    {id:  102, fromDate: new Date("2022-11-30"), toDate: new Date("2022-11-30")}, 
    ];

  var db = new alasql.Database("MyDB");
  db.exec('CREATE TABLE mytable (id INT, fromDate Date, toDate Date)');
  db.tables.mytable.data = data;

  console.log(db.tables.mytable.data);
  var res = db.exec(`SELECT id FROM mytable ORDER BY fromDate, id ASC`,);

  console.log(res);
}
```

The result I get:

`[ {id: 200}, {id: 102}, {id: 101}, {id: 100} ]`

But the result I expect is:

`[ {id: 200}, {id: 100}, {id: 101}, {id: 102} ]`

Any idea of what's happening ?

**Comment by fabads** [comment] 2022-10-05 16:35
With the JSFiddle:
[http://jsfiddle.net/crf3nvj6/](url)

**Comment by fabads** [comment] 2022-10-06 15:25
Yes you are right, deeply linked to the Javascript date format. I tried to use string date (YYYYMMDD) and the double ordering is working fine. In my case, I do not have the choice, my data source contains javascript dates already.

**Comment by Buroni** [comment] 2022-10-07 15:16
I've spent some time looking into this issue. It seems like there's several factors involved.

This seems to be partially fixed on the `develop` branch for `2.1.3`. If I recreate @fabads' example in a local test on `develop`, it reproduces the error. However if I add `fromDate` to the select query columns then it works as we'd expect.

```sql
# This doesn't work on `develop`
SELECT id FROM mytable ORDER BY fromDate, id ASC

# This does work
SELECT id, fromDate FROM mytable ORDER BY fromDate, id ASC
```

The issue here is that the date needs to be converted to a Unix epoch via `date.valueOf()`. This only happens when the column type explicitly is `DATE`, `DATETIME`, `STRING` or `NUMBER`: see [426orderby.js#L60](https://github.com/AlaSQL/alasql/blob/develop/src/426orderby.js#L60). However, the `fromDate` column as well as all associated type information is dropped out of the subquery object when it's not explicitly `SELECT`ed in the subquery.

This is also what causes the issue in @mathiasrw's example, although in a different way. Since it's an anonymous query, there's no type information for `date` so the `.valueOf()` prefix is never added to the date. Therefore the dates are compared as strings rather than Unix epochs.

I'm looking into how to get round this, but someone more familiar with the codebase may be able to make a quicker fix with this information!

**Comment by mathiasrw** [comment] 2022-10-08 23:16
Nice work @Buroni. Very nice work...

**Comment by mathiasrw** [comment] 2022-12-27 04:06
Any luck @Buroni ?

**Comment by Buroni** [comment] 2023-03-07 20:53
@mathiasrw oh it's been a while.. Digging into it now

**Comment by Buroni** [comment] 2023-03-08 08:35
@mathiasrw Do you know the reason why `alasql.options.valueOf = false;` by default? Is there some non-primitive type whose ordering would be broken by getting its `valueOf`? A quick fix would be to set this default to `true`. Within the current structure I can't see another way to solve the problem for anonymous queries, as determining whether to get `valueOf` depends on type information which anonymous queries don't have.

**Comment by mathiasrw** [comment] 2023-03-09 01:29
> Do you know the reason why alasql.options.valueOf = false; by default?

Probably for backwards compatibility. Happy to change it and bump up to v4

**Closed** 2023-03-12 22:23 UTC
Labels: ! Bug, Help wanted, Related to: SQL compliance, Bug: Code provided to reproduced, Good first issue
